### ISSUE TITLE
Can not hook api RegGetValueW api in advapi32 module

### ISSUE THREAD

**Issue by funte** [mrexodia/AppInitHook#3]
Environment:
```
os: win10 21H1 x64
ide: vs2022
cmake: 3.24
```

Reproduce steps:  
Modify the AppInitExampleModule  project, remove all other hooks and add this code.  
When only hook the api RegGetValueW,  call it in TestLoader project, but the DebugView output nothing, the RegGetValueW is not replaced.  
```c
HOOK(advapi32, LSTATUS WINAPI, RegGetValueW)(
	_In_ HKEY hkey,
	_In_opt_ LPCWSTR lpSubKey,
	_In_opt_ LPCWSTR lpValue,
	_In_ DWORD dwFlags,
	_Out_opt_ LPDWORD pdwType,
	_Out_ PVOID pvData,
	_Inout_opt_ LPDWORD pcbData)
{
	return 123;
}
```

Then add this code to AppInitExampleModule  project, replace the api GetSystemMetrics in user32 module:  
```c
HOOK(user32.dll, int WINAPI, GetSystemMetrics)(_In_ int nIndex)
{
	if (nIndex == SM_REMOTESESSION) {
		return 0;
	} else {
		return original_GetSystemMetrics(nIndex);
	}
}
```

Finally, call these two api RegGetValueW and GetSystemMetrics in TestLoader  project ,they are both replaced!!

**Comment by mrexodia** [comment]
What does DebugView say when you start?

**Comment by funte** [comment]
> What does DebugView say when you start?

Just hook RegGetValueW and call it in TestLoader, the DebugView output nothing, you can do this reproduce it:  
1. Add this to AppInitExampleModule project and clear all other hooks:  
```c
HOOK(advapi32, LSTATUS WINAPI, RegGetValueW)(
	_In_ HKEY hkey,
	_In_opt_ LPCWSTR lpSubKey,
	_In_opt_ LPCWSTR lpValue,
	_In_ DWORD dwFlags,
	_Out_opt_ LPDWORD pdwType,
	_Out_ PVOID pvData,
	_Inout_opt_ LPDWORD pcbData)
{
	return 123;
}
```
2. Add this to TestLoader project:  
```c
#include <iostream>
#include <windows.h>

int main() {
	//// Uncomment this,  the RegGetValueW hook will work!!! 
	//if (GetSystemMetrics(SM_REMOTESESSION) == 0) {
	//	std::cout << "Is remote session: NO" << std::endl;
	//} else {
	//	std::cout << "Is remote session: YES" << std::endl;
	//}

	DWORD dwType = 0;
	WCHAR value[255] = {};
	DWORD dataSize = 255;

	std::wstring subkey = std::wstring(L"SYSTEM\\CurrentControlSet\\Control\\SystemInformation");
	std::wstring valuekey = std::wstring(L"SystemManufacturer");
	dataSize = 255;
	LSTATUS status = RegGetValueW(
		HKEY_LOCAL_MACHINE, subkey.c_str(), valuekey.c_str(),
		RRF_RT_REG_SZ, &dwType, value, &dataSize);
	if (status == ERROR_SUCCESS) {
		std::wcout << "SystemManufacturer = " << std::wstring(value) << std::endl;
	} else {
		std::cout << "Failed to get SystemManufacturer, errcode = " << status << std::endl;
	}

	subkey = std::wstring(L"SYSTEM\\CurrentControlSet\\Control\\SystemInformation");
	valuekey = std::wstring(L"SystemProductName");
	dataSize = 255;
	status = RegGetValueW(
		HKEY_LOCAL_MACHINE, subkey.c_str(), valuekey.c_str(),
		RRF_RT_REG_SZ, &dwType, value, &dataSize);
	if (status == ERROR_SUCCESS) {
		std::wcout << "SystemProductName = " << std::wstring(value) << std::endl;
	} else {
		std::cout << "Failed to get SystemProductName, errcode = " << status << std::endl;
	}

	std::string subkey2 = std::string("SOFTWARE\\Microsoft\\Cryptography");
	HKEY hkey = NULL;
	status = RegOpenKeyExA(HKEY_LOCAL_MACHINE, subkey2.c_str(), 0, KEY_READ, &hkey);
	if (status == ERROR_SUCCESS) {
		CHAR value2[255] = {};
		dataSize = 255;
		std::string valuekey2 = std::string("MachineGuid");
		status = RegQueryValueExA(hkey, valuekey2.c_str(), NULL, &dwType, (LPBYTE)value2, &dataSize);
		if (status == ERROR_SUCCESS) {
			std::cout << "MachineGuid = " << value2 << std::endl;
		} else {
			std::cout << "Failed to get MachineGuid, errcode = " << GetLastError() << std::endl;
		}
	} else {
		std::cout << "Failed to open SOFTWARE\\Microsoft\\Cryptography, errcode = " << GetLastError() << std::endl;
	}

	return 0;
}

```

**Comment by mrexodia** [comment]
DebugView should report which hooks were applied etc. Please share the logs

**Comment by funte** [comment]
Only hook and call RegGetValueW, the DebugBiew output nothing:  
![1](https://user-images.githubusercontent.com/9884836/194264967-0b4ceec1-e76e-467b-b6ad-fbb0d83de5a2.png)

Both hook RegGetValueW, RegGetValueW  and call them, the output:  
![2](https://user-images.githubusercontent.com/9884836/194265294-87352bd4-7071-4145-997d-d61bd5f77a73.png)

**Comment by mrexodia** [comment]
Your hook is not applied, are you calling the DllMain of AppInitHook? Please show the full source code of your DLL with the HOOK macro.

**Comment by mrexodia** [comment]
Actually nevermind, it looks like the hook is applied.

**Comment by mrexodia** [comment]
Did you figure out the problem?

**Comment by mrexodia** [comment]
Ah, likely the issue was that `TestLoader.exe` no longer imports `user32.dll`, which means that `AppInit_DLLs` aren't loaded...

**Comment by funte** [comment]
I have move my project directly use the MinHook, and write some dummy macros to support virtual table and general api hooks, but i find another issue, `CreateDXGIFactory` will hook fails with using `MH_CreateHookApi`, maybe the  `HookDllMain`  should try `GetProcAddress` and `MH_CreateHook` after calling `MH_CreateHookApi` fails.
